import { sleep } from 'antd-mobile/es/utils/sleep'

let count = 0

export async function mockRequest() {
  if (count >= 5) {
    return []
  }
  await sleep(2000)
  count++
  return [
    
      {
          "vehicleId": null,
          "vehicleName": null,
          "licensePlate": null,
          "vehicleType": "6",
          "vehicleTypeName": null,
          "vehicleMake": null,
          "vehicleModel": null,
          "vehicleYear": null,
          "vehicleColor": "白色",
          "vehicleOwner": null,
          "vehicleOwnerName": null,
          "vehicleStatus": null,
          "vehicleStatusName": null,
          "lastServiceDate": null,
          "mileage": null,
          "insuranceExpiry": null,
          "instUserid": null,
          "instDate": null,
          "updUserid": null,
          "updDate": null,
          "remark": null,
          "ownerName": null,
          "ownerIdNumber": null,
          "ownerTel": null,
          "orgName": null,
          "trackingCardId": null,
          "id": null,
          "expiryTime": null,
          "vehicleStatistics": null,
          "vehicleNumber": "粤Q06416",
          "vehicleTypeShow": "大货车",
          "department": "综合管理部",
          "vehicleKind": "1",
          "vehicleKindShow": "内部"
      },
      {
          "vehicleId": null,
          "vehicleName": null,
          "licensePlate": null,
          "vehicleType": "6",
          "vehicleTypeName": null,
          "vehicleMake": null,
          "vehicleModel": null,
          "vehicleYear": null,
          "vehicleColor": "白色",
          "vehicleOwner": null,
          "vehicleOwnerName": null,
          "vehicleStatus": null,
          "vehicleStatusName": null,
          "lastServiceDate": null,
          "mileage": null,
          "insuranceExpiry": null,
          "instUserid": null,
          "instDate": null,
          "updUserid": null,
          "updDate": null,
          "remark": null,
          "ownerName": null,
          "ownerIdNumber": null,
          "ownerTel": null,
          "orgName": null,
          "trackingCardId": null,
          "id": null,
          "expiryTime": null,
          "vehicleStatistics": null,
          "vehicleNumber": "粤QHD110",
          "vehicleTypeShow": "大货车",
          "department": "综合管理部",
          "vehicleKind": "1",
          "vehicleKindShow": "内部"
      },
      {
          "vehicleId": null,
          "vehicleName": null,
          "licensePlate": null,
          "vehicleType": "1",
          "vehicleTypeName": null,
          "vehicleMake": null,
          "vehicleModel": null,
          "vehicleYear": null,
          "vehicleColor": null,
          "vehicleOwner": null,
          "vehicleOwnerName": null,
          "vehicleStatus": null,
          "vehicleStatusName": null,
          "lastServiceDate": null,
          "mileage": null,
          "insuranceExpiry": null,
          "instUserid": null,
          "instDate": null,
          "updUserid": null,
          "updDate": null,
          "remark": null,
          "ownerName": null,
          "ownerIdNumber": null,
          "ownerTel": null,
          "orgName": null,
          "trackingCardId": null,
          "id": null,
          "expiryTime": null,
          "vehicleStatistics": null,
          "vehicleNumber": "粤D08965",
          "vehicleTypeShow": "大巴车",
          "department": "综合管理部",
          "vehicleKind": "1",
          "vehicleKindShow": "内部"
      },
      {
          "vehicleId": null,
          "vehicleName": null,
          "licensePlate": null,
          "vehicleType": "6",
          "vehicleTypeName": null,
          "vehicleMake": null,
          "vehicleModel": null,
          "vehicleYear": null,
          "vehicleColor": "白色",
          "vehicleOwner": null,
          "vehicleOwnerName": null,
          "vehicleStatus": null,
          "vehicleStatusName": null,
          "lastServiceDate": null,
          "mileage": null,
          "insuranceExpiry": null,
          "instUserid": null,
          "instDate": null,
          "updUserid": null,
          "updDate": null,
          "remark": null,
          "ownerName": null,
          "ownerIdNumber": null,
          "ownerTel": null,
          "orgName": null,
          "trackingCardId": null,
          "id": null,
          "expiryTime": null,
          "vehicleStatistics": null,
          "vehicleNumber": "粤Q06463",
          "vehicleTypeShow": "大货车",
          "department": "综合管理部",
          "vehicleKind": "1",
          "vehicleKindShow": "内部"
      },
      {
          "vehicleId": null,
          "vehicleName": null,
          "licensePlate": null,
          "vehicleType": "6",
          "vehicleTypeName": null,
          "vehicleMake": null,
          "vehicleModel": null,
          "vehicleYear": null,
          "vehicleColor": "蓝色",
          "vehicleOwner": null,
          "vehicleOwnerName": null,
          "vehicleStatus": null,
          "vehicleStatusName": null,
          "lastServiceDate": null,
          "mileage": null,
          "insuranceExpiry": null,
          "instUserid": null,
          "instDate": null,
          "updUserid": null,
          "updDate": null,
          "remark": null,
          "ownerName": null,
          "ownerIdNumber": null,
          "ownerTel": null,
          "orgName": null,
          "trackingCardId": null,
          "id": null,
          "expiryTime": null,
          "vehicleStatistics": null,
          "vehicleNumber": "粤QGL331",
          "vehicleTypeShow": "大货车",
          "department": "综合管理部",
          "vehicleKind": "1",
          "vehicleKindShow": "内部"
      }
  
  ]
}